language: generic
sudo: required
services:
   - docker

before_install:
  - docker build -t diiegg/docker-react -f Dockerfile.dev .

script:
  - docker run diiegg/docker-react npm run test -- --coverage
